# Generated by Django 4.2 on 2023-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('login', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
